[base]
database = 'database.db'
queue = 'queue.db'
secret = 'PLACEHOLDER'

[web]
uri = 'https://reporteao.net'

[email]
host = 'example.net'
port = 465
address = 'noreply@example.net'
username = 'noreply'
password = 'PLACEHOLDER'
